### ISSUE TITLE
Validating if exists

### ISSUE THREAD

**Issue by juanibe** [donpapitoskey/nodeChallengePuzzle#4]
Case: When we perform a query or mutation and we need to validate the existence of the resource for example in your code:

`if(user === undefined)`

When using undefined or null you need to ask yourself: could the value, given another input/state/context be defined to something?
If the answer is yes then use null else use undefined. More generally any function returning an object should return null when the intended object does not exist. Because it could exist given another input/state/context. (Source: stackoverflow)

This is theory, but I personally rather use: 

`if(!user)`

However, to make your code more robust and consistent and less tending to errors you could do:

`if(user === undefined || user === null){...}`

**Comment by donpapitoskey** [comment]
Solved. Checking for both `undefined` and `null` when required
